package.json fix & testing new pre-push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,11 +1,18 @@
-npm run demo:build
-DEMO_RESULT=$?
+webpack -c ./webpack.js
+WEBPACK_RESULT=$?
 
-if [ $DEMO_RESULT -ne 0 ]; then
-  echo "npm run demo failed with exit code $DEMO_RESULT. Push aborted."
+if [ $WEBPACK_RESULT$ -ne 0 ]; then
+  echo "webpack -c /webpack.js failed with exit code $WEBPACK_RESULT. Push aborted."
   exit 1
 fi
 
+npm run typecheck
+TYPECHECK_RESULT=$?
+
+if [ $TYPECHECK_RESULT -ne 0 ]; then
+  echo "npm run typecheck failed with exit code $TYPECHECK_RESULT. Push aborted."
+  exit 1
+fi
 
 npm run test
 TEST_RESULT=$?
